module.exports = [
  "Whispering Pines Campground",
  "Silver Birch Retreat",
  "Cedar Ridge Campsites",
  "Sunset Hollow",
  "Timberline Grove",
  "Golden Valley Camp",
  "Wildflower Meadows",
  "Mountain Creek Retreat",
  "Starlight Haven",
  "Pinecone Point",
  "Riverbend Camp",
  "Maplewood Pines",
  "Bear Tracks Campsite",
  "Crystal Springs Resort",
  "Echo Valley Campground",
  "Redwood Grove",
  "Rocky Ridge Wilderness",
  "Sierra Ridge Camp",
  "Blue Sky Meadows",
  "Hidden Falls Campground",
  "Evergreen Hollow",
  "Thunder Mountain Camp",
  "Shady Pines Resort",
  "Wildwood Springs",
  "Lakeview Heights Campground",
  "Boulder Ridge Campsites",
  "Quiet Brook Retreat",
  "Windy Ridge Campsites",
  "Fox Run Campground",
  "Sunrise Summit",
  "Moonlit Meadows",
  "Fallen Leaf Campsites",
  "Whitetail Acres",
  "Crimson Canyon Campground",
  "Crystal Lake Retreat",
  "Silverstone Wilderness",
  "Lost Pines Retreat",
  "Hawk's Nest Campsites",
  "Sagebrush Ridge",
  "Timberwolf Crossing",
  "Bluebird Bluff",
  "Misty Mountain Retreat",
  "Turtle Bay Campground",
  "Sunset Ridge Trails",
  "Frosted Glen Campsites",
  "Pine Hill Sanctuary",
  "Snowberry Ridge Camp",
  "Rock Creek Campground",
  "Dewdrop Hollow",
  "Rainbow Ridge Campground",
]
